version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praktika_bot
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./migrations:/app/migrations
    networks:
      - bot_network
    environment:
      - TZ=Europe/Moscow

  postgres:
    image: postgres:15-alpine
    container_name: praktika_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-test_bot}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data: